service: foodflation-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
	
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-warmup

functions:
  app:
    handler: src/index.handler
    events:
      - httpApi: "*"
